events/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from .views import (EventDetail,
                    EventList,
                    EventCreate,
                    EventUpdate,
                    EventDelete,
                    EventsFeed)

urlpatterns = patterns('',
                       url(r'^$', EventList.as_view(), name='events_list_all'),
                       url(r'^rss$', EventsFeed(), name='events_feed'),
                       url(r'^(?P<pk>\d+)/$', EventDetail.as_view(), name='detail'),
                       url(r'^add/$', EventCreate.as_view(), name='add'),
                       url(r'^(?P<pk>\d+)/edit/$', EventUpdate.as_view(), name='edit'),
                       url(r'^(?P<pk>\d+)/delete/$', EventDelete.as_view(), name='delete'),
                       )

faq/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from .views import (
    list_all,
)

urlpatterns = patterns('', url(r'^$', list_all, name='faq_all'),)

planet/urls.py
# -*- coding: utf-8 -*-
try:
    # Django 1.6
    from django.conf.urls import patterns, url, include
except ImportError:
    # Django < 1.6
    from django.conf.urls.defaults import patterns, url

from django.contrib.sitemaps import views as sitemaps_views
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required

from planet.views import (FeedFormView, BlogByUserList, BlogDelete,
                          FeedDelete, PostDelete)
from planet.feeds import PostFeed, AuthorFeed, AuthorTagFeed, TagFeed
from planet.sitemaps import planet_sitemaps_dict


urlpatterns = patterns('planet.views',
                       url(r'^blogs/(?P<blog_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "blog_detail", name="planet_blog_detail"),
                       url(r'^blogs/(?P<blog_id>\d+)/$', "blog_detail"),
                       url(r'^blogs/(?P<pk>\d+)/delete$',
                           login_required(BlogDelete.as_view()), name="planet_blog_delete"),
                       url(r'^blogs/$', "blogs_list", name="planet_blog_list"),
                       url(r'^blogs/my_blogs/$', login_required(BlogByUserList.as_view()),
                           name="planet_blog_list_by_user"),

                       url(r'^feeds/add/$', login_required(FeedFormView.as_view()),
                           name="feed_add"),
                       url(r'^feeds/(?P<feed_id>\d+)/delete/$',
                           login_required(FeedDelete.as_view()), name="feed_delete"),
                       url(r'^feeds/(?P<feed_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/tags/(?P<tag>.*)/$',
                           "feed_detail", name="planet_by_tag_feed_detail"),
                       url(r'^feeds/(?P<feed_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "feed_detail", name="planet_feed_detail"),
                       url(r'^feeds/(?P<feed_id>\d+)/$', "feed_detail"),
                       url(r'^feeds/$', "feeds_list", name="planet_feed_list"),

                       url(r'^authors/(?P<author_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/tags/(?P<tag>.*)/$',
                           "author_detail", name="planet_by_tag_author_detail"),
                       url(r'^authors/(?P<author_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "author_detail", name="planet_author_detail"),
                       url(r'^authors/(?P<author_id>\d+)/$', "author_detail"),
                       url(r'^authors/$', "authors_list",
                           name="planet_author_list"),

                       url(r'^tags/(?P<tag>.*)/feeds/$',
                           "tag_feeds_list", name="planet_tag_feed_list"),
                       url(r'^tags/(?P<tag>.*)/authors/$',
                           "tag_authors_list", name="planet_tag_author_list"),
                       url(r'^tags/(?P<tag>.*)/$', "tag_detail",
                           name="planet_tag_detail"),
                       url(r'^tags/$', "tags_cloud", name="planet_tag_cloud"),

                       url(r'^opml/$', "opml", name="planet_opml"),
                       url(r'^foaf/$', "foaf", name="planet_foaf"),

                       url(r'^posts/(?P<post_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "post_detail", name="planet_post_detail"),
                       url(r'^posts/(?P<pk>\d+)/$', login_required(PostDelete.as_view()),
                           name="planet_post_delete"),
                       url(r'^posts/(?P<post_id>\d+)/$', "post_detail"),
                       url(r'^posts/$', "posts_list", name="planet_post_list"),

                       url(r'^search/$', "search", name="planet_search"),

                       url(r'^$', "index", name="planet_index"),
                       )

# Feed's urls
urlpatterns += patterns('',
                        url(r'^posts/feeds/rss/$', PostFeed(),
                            name="planet_rss_feed"),
                        url(r'^feeds/rss/tags/(?P<tag>.*)/$',
                            TagFeed(), name="planet_tag_rss_feed"),
                        url(r'^feeds/rss/authors/(?P<author_id>\d+)/$',
                            AuthorFeed(), name="planet_author_rss_feed"),
                        url(r'^feeds/rss/authors/(?P<author_id>\d+)/tags/(?P<tag>.*)/$',
                            AuthorTagFeed(), name="planet_tag_author_rss_feed"),
                        )

# sitemaps
urlpatterns += patterns('',
                        url(r'^sitemap.xml$',
                            cache_page(86400)(sitemaps_views.index),
                            {'sitemaps': planet_sitemaps_dict, 'sitemap_url_name': 'sitemaps'}),
                        url(r'^sitemap-(?P<section>.+)\.xml$',
                            cache_page(86400)(sitemaps_views.sitemap),
                            {'sitemaps': planet_sitemaps_dict}, name='sitemaps'),
                        )

pyarweb/urls.py
# -*- coding: utf-8 -*-


"""URLS configurations for PyAr Web."""


from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from waliki.settings import WALIKI_SLUG_PATTERN

from .views import buscador, irc, old_url_redirect


admin.autodiscover()


urlpatterns = patterns(
    '',
    # Static files
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    # Media files
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    url(r'^irc/$', irc, name='irc'),
    url(r'^buscador/$', buscador, name='buscador'),

    url(r'^$', 'community.views.homepage', name='homepage'),
    url(r'^aprendiendo-python/', 'community.views.learning', name='aprendiendo'),
    url(r'^nosotros/', 'community.views.about_pyar', name='about_pyar'),
    url(r'^miembros/', 'community.views.members', name='pyar_members'),
    url(r'^lista/', 'community.views.mailing_list', name='mailing_list'),

    url(r'^noticias/', include('news.urls')),
    url(r'^empresas/', include('pycompanies.urls', namespace='companies')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^trabajo/', include('jobs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^eventos/', include('events.urls', namespace='events')),
    # Descomentar cuando planet este funcionando
    # url(r'^planeta/', include('planet.urls')),
    # No se que va a pasar con la app de newbie, lanzamos primer release y
    # lo comento hasta que se decida que se hace
    # url(r'^newbie/', include('newbie.urls')),
    # No se que va a pasar con la app de project, lanzamos primer release y
    # lo comento hasta que se decida que se hace
    # url(r'^projects/', include('projects.urls')),
    # url(r'^faq/', include('faq.urls')),
    url(r'^wiki/', include('waliki.urls')),
    url(r'^(pyar/)?(?P<slug>' + WALIKI_SLUG_PATTERN + ')/?',
        old_url_redirect, name='old_url_redirect'),
)

pycompanies/urls.py
from django.conf.urls import patterns, url

from .views import (
    CompanyDetail,
    CompanyList,
    CompanyCreate,
    CompanyUpdate,
    CompanyDelete)

urlpatterns = patterns('',
    url(r'^$', CompanyList.as_view(), name='company_list_all'),
    url(r'^(?P<pk>\d+)/$', CompanyDetail.as_view(), name='detail'),
    url(r'^add/$', CompanyCreate.as_view(), name='add'),
    url(r'^(?P<pk>\d+)/edit/$', CompanyUpdate.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', CompanyDelete.as_view(), name='delete'),
)

templates/companies/company_confirm_delete.html
{% extends "base.html" %}

{% load i18n %}

{% load devtags %}

{% block content %}

    <main id="main" class="container" role="main">
        <div class="row">
            <div class="col-md-12">
                <form method="post">{% csrf_token %}
                    {% trans "Are you sure you want to delete" %} "{{ object.name }}" ?
                    <input type="submit" value="Yes" class="btn btn-danger">
                    <a href="{% url 'companies:company_list_all' %}" class="btn btn-default">No</a>
                </form>
            </div>
        </div>
    </main>

{% endblock %}

templates/companies/company_detail.html
{% extends "base.html" %}
{% load disqus_tags %}
{% load i18n %}
{% load staticfiles %}
{% load devtags %}
{% block title %}
  {{ object.title }}
{% endblock title %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
      <div class="page-header">
        <h2>
          {{ object.name }}
          <span class="pull-right">
            {% if object.owner == user %}
            <a href="{% url 'companies:edit' object.id %}" class="btn btn-info">{% trans 'Editar' %}</a>
            <a href="{% url 'companies:delete' object.id %}" class="btn btn-danger">{% trans 'Borrar' %}</a>
            {% endif %}
          </span>
        </h2>
      </div>
      <div class="row">
        <div class="col-md-8">
          <article>
            <p>{% autoescape off %}{{ object.description|linebreaks|safe }}{% endautoescape %}</p>
          </article>
        </div>
        <div class="col-md-4">
          <a href="{{ object.link }}" target="blank">
            <img style="max-width:200px; height:auto;" src="{{ MEDIA_URL }}{{ object.photo }}"></img>
          </a>
        </div>
      </div>
  </div>
</main>
{% endblock %}

templates/companies/company_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block stylesheets %}
  <link rel="stylesheet" href="/static/css/event_map.css">
{% endblock %}

{% block content %}
	<main id="main" class="container" role="main">
	    <div class="col-lg-12">
		    <div class="page-header">
		    	<h2>{% if form.instance.id %}
		    			{% trans 'Editar Empresa' %}
		    		{% else %}
		    			{% trans 'Agregar Empresa' %}
		    		{% endif %}
		    	</h2>
		    </div>
		    {{ form.media }}
		    {% crispy form %}
		</div>
	</main>
{% endblock %}

templates/companies/company_list.html
{% extends "base_site.html" %}
{% load devtags %}
{% load i18n staticfiles pagination_tags devtags %}
{% block title %}Empresas que utilizan Python{% endblock %}
{% block left-column %}
  <!-- Empresas que utilizan python -->
  <section>
      <div class="col-md-12">
          <div class="page-header">
              <h2>{% trans 'Empresas que utilizan Python' %}
                  <span class="section-button-group pull-right">
                      <a href="{% url 'companies:add' %}" class="btn btn-info">{% trans 'Agregar Empresa' %}</a>
                  </span>
              </h2>
          </div>
          {% if object_list %}
              {% for object in object_list %}
                <h3>
                    <a href="{{ object.get_absolute_url }}">{{ object.name }}</a> 
                </h3>
                <p>{{ object.description|striptags|truncatewords:"20" }}</p>
                <p><a href="{{ object.get_absolute_url }}">{% trans 'Más información...' %}</a></p>
              {% endfor %}

              {% paginate %}
          {% else %}
              <div class="col-md-12">
                  <p>{% trans 'La búsqueda no produjo resultados.' %}</p>
              </div>
          {% endif %}
      </div>
  </section>
{% endblock %}

{% block right-column %}
  {{ block.super }}
  {% include "_tags_filtering_form.html" %}
{% endblock %}