faq/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from .views import (
    list_all,
)

urlpatterns = patterns('', url(r'^$', list_all, name='faq_all'),)

planet/urls.py
# -*- coding: utf-8 -*-
try:
    # Django 1.6
    from django.conf.urls import patterns, url, include
except ImportError:
    # Django < 1.6
    from django.conf.urls.defaults import patterns, url

from django.contrib.sitemaps import views as sitemaps_views
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required

from planet.views import (FeedFormView, BlogByUserList, BlogDelete,
                          FeedDelete, PostDelete)
from planet.feeds import PostFeed, AuthorFeed, AuthorTagFeed, TagFeed
from planet.sitemaps import planet_sitemaps_dict


urlpatterns = patterns('planet.views',
                       url(r'^blogs/(?P<blog_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "blog_detail", name="planet_blog_detail"),
                       url(r'^blogs/(?P<blog_id>\d+)/$', "blog_detail"),
                       url(r'^blogs/(?P<pk>\d+)/delete$',
                           login_required(BlogDelete.as_view()), name="planet_blog_delete"),
                       url(r'^blogs/$', "blogs_list", name="planet_blog_list"),
                       url(r'^blogs/my_blogs/$', login_required(BlogByUserList.as_view()),
                           name="planet_blog_list_by_user"),

                       url(r'^feeds/add/$', login_required(FeedFormView.as_view()),
                           name="feed_add"),
                       url(r'^feeds/(?P<feed_id>\d+)/delete/$',
                           login_required(FeedDelete.as_view()), name="feed_delete"),
                       url(r'^feeds/(?P<feed_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/tags/(?P<tag>.*)/$',
                           "feed_detail", name="planet_by_tag_feed_detail"),
                       url(r'^feeds/(?P<feed_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "feed_detail", name="planet_feed_detail"),
                       url(r'^feeds/(?P<feed_id>\d+)/$', "feed_detail"),
                       url(r'^feeds/$', "feeds_list", name="planet_feed_list"),

                       url(r'^authors/(?P<author_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/tags/(?P<tag>.*)/$',
                           "author_detail", name="planet_by_tag_author_detail"),
                       url(r'^authors/(?P<author_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "author_detail", name="planet_author_detail"),
                       url(r'^authors/(?P<author_id>\d+)/$', "author_detail"),
                       url(r'^authors/$', "authors_list",
                           name="planet_author_list"),

                       url(r'^tags/(?P<tag>.*)/feeds/$',
                           "tag_feeds_list", name="planet_tag_feed_list"),
                       url(r'^tags/(?P<tag>.*)/authors/$',
                           "tag_authors_list", name="planet_tag_author_list"),
                       url(r'^tags/(?P<tag>.*)/$', "tag_detail",
                           name="planet_tag_detail"),
                       url(r'^tags/$', "tags_cloud", name="planet_tag_cloud"),

                       url(r'^opml/$', "opml", name="planet_opml"),
                       url(r'^foaf/$', "foaf", name="planet_foaf"),

                       url(r'^posts/(?P<post_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "post_detail", name="planet_post_detail"),
                       url(r'^posts/(?P<pk>\d+)/$', login_required(PostDelete.as_view()),
                           name="planet_post_delete"),
                       url(r'^posts/(?P<post_id>\d+)/$', "post_detail"),
                       url(r'^posts/$', "posts_list", name="planet_post_list"),

                       url(r'^search/$', "search", name="planet_search"),

                       url(r'^$', "index", name="planet_index"),
                       )

# Feed's urls
urlpatterns += patterns('',
                        url(r'^posts/feeds/rss/$', PostFeed(),
                            name="planet_rss_feed"),
                        url(r'^feeds/rss/tags/(?P<tag>.*)/$',
                            TagFeed(), name="planet_tag_rss_feed"),
                        url(r'^feeds/rss/authors/(?P<author_id>\d+)/$',
                            AuthorFeed(), name="planet_author_rss_feed"),
                        url(r'^feeds/rss/authors/(?P<author_id>\d+)/tags/(?P<tag>.*)/$',
                            AuthorTagFeed(), name="planet_tag_author_rss_feed"),
                        )

# sitemaps
urlpatterns += patterns('',
                        url(r'^sitemap.xml$',
                            cache_page(86400)(sitemaps_views.index),
                            {'sitemaps': planet_sitemaps_dict, 'sitemap_url_name': 'sitemaps'}),
                        url(r'^sitemap-(?P<section>.+)\.xml$',
                            cache_page(86400)(sitemaps_views.sitemap),
                            {'sitemaps': planet_sitemaps_dict}, name='sitemaps'),
                        )

pyarweb/urls.py
# -*- coding: utf-8 -*-


"""URLS configurations for PyAr Web."""


from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from waliki.settings import WALIKI_SLUG_PATTERN

from .views import buscador, irc, old_url_redirect


admin.autodiscover()


urlpatterns = patterns(
    '',
    # Static files
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    # Media files
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    url(r'^irc/$', irc, name='irc'),
    url(r'^buscador/$', buscador, name='buscador'),

    url(r'^$', 'community.views.homepage', name='homepage'),
    url(r'^aprendiendo-python/', 'community.views.learning', name='aprendiendo'),
    url(r'^nosotros/', 'community.views.about_pyar', name='about_pyar'),
    url(r'^miembros/', 'community.views.members', name='pyar_members'),
    url(r'^lista/', 'community.views.mailing_list', name='mailing_list'),

    url(r'^noticias/', include('news.urls')),
    url(r'^empresas/', include('pycompanies.urls', namespace='companies')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^trabajo/', include('jobs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^eventos/', include('events.urls', namespace='events')),
    # Descomentar cuando planet este funcionando
    # url(r'^planeta/', include('planet.urls')),
    # No se que va a pasar con la app de newbie, lanzamos primer release y
    # lo comento hasta que se decida que se hace
    # url(r'^newbie/', include('newbie.urls')),
    # No se que va a pasar con la app de project, lanzamos primer release y
    # lo comento hasta que se decida que se hace
    # url(r'^projects/', include('projects.urls')),
    # url(r'^faq/', include('faq.urls')),
    url(r'^wiki/', include('waliki.urls')),
    url(r'^(pyar/)?(?P<slug>' + WALIKI_SLUG_PATTERN + ')/?',
        old_url_redirect, name='old_url_redirect'),
)

planet/models.py
# -*- coding: utf-8 -*-

"""
    django-planet models

    Heavily based on Feedjack's [1] models by Gustavo Picón. Changes and addings
    inspired by Mark Pilgrim's Feedparser [2].

    [1] http://www.feedjack.org/
    [2] http://www.feedparser.org/
"""

# python 3.x compatibility helpers
from django.utils.encoding import python_2_unicode_compatible

import feedparser
from datetime import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.sites.models import Site
from django.conf import settings
from django.db.models.signals import pre_delete
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

import tagging
from tagging.models import Tag

from planet.managers import (FeedManager, AuthorManager, BlogManager,
    PostManager, GeneratorManager, PostLinkManager, FeedLinkManager,
    EnclosureManager)


@python_2_unicode_compatible
class Blog(models.Model):
    """
    A model to store primary info about a blog or website that which feed or
    feeds are aggregated to our planet
    """
    owner = models.ForeignKey(User, null=True, blank=True)
    title = models.CharField(_("title"), max_length=255, blank=True, db_index=True)
    url = models.URLField(_("Url"), unique=True, db_index=True)
    date_created = models.DateTimeField(_("Date created"), auto_now_add=True)

    site_objects = BlogManager()
    objects = models.Manager()

    class Meta:
        verbose_name = _("Blog")
        verbose_name_plural = _("Blogs")
        ordering = ('title', 'url',)

    def __str__(self):
        return '{} ({})'.format(self.title, self.url)

    @models.permalink
    def get_absolute_url(self):
        return ('planet.views.blog_detail', [str(self.id), self.get_slug()])

    def get_slug(self):
        return slugify(self.title) or "no-title"


@python_2_unicode_compatible
class Generator(models.Model):
    """
    The software or website that has built a feed
    """
    name = models.CharField(_("Name"), max_length=100)
    link = models.URLField(_("Url"), blank=True, null=True)
    version = models.CharField(_("Version"), max_length=200, blank=True, null=True)

    site_objects = GeneratorManager()
    objects = models.Manager()

    class Meta:
        verbose_name = _("Generator")
        verbose_name_plural = _("Generators")
        ordering = ('name', 'version',)
        unique_together = (("name", "link", "version"), )

    def __str__(self):
        return '{} {} ({})'.format(self.name, self.version or "", self.link or "--")


@python_2_unicode_compatible
class Category(models.Model):
    """
    Define Categories for Feeds. In this way a site can manage many
    aggregator/planet
    """
    title = models.CharField(_("Category Title"), max_length=100, unique=True)
    date_created = models.DateField(_("Date created"), auto_now_add=True)

    class Meta:
        verbose_name = _("Feed Category")
        verbose_name_plural = _("Feed Categories")
        ordering = ('title', 'date_created')

    def __str__(self):
        return "{}".format(self.title)


@python_2_unicode_compatible
class Feed(models.Model):
    """
    A model to store detailed info about a parsed Atom or RSS feed
    """
    # a feed belongs to a blog
    blog = models.ForeignKey("planet.Blog", null=True, blank=True)
    # a site where this feed is published
    site = models.ForeignKey(Site, null=True, blank=True, db_index=True)
    # url to retrieve this feed
    url = models.URLField(_("Url"), unique=True, db_index=True)
    # title attribute from Feedparser's Feed object
    title = models.CharField(_("Title"), max_length=255, db_index=True,
        blank=True, null=True)
    # subtitle attribute from Feedparser's Feed object. aka tagline
    subtitle = models.TextField(_("Subtitle"), blank=True, null=True)
    # rights or license attribute from Feedparser's Feed object
    rights = models.CharField(_("Rights"), max_length=255, blank=True,
                              null=True)
    # generator_detail attribute from Feedparser's Feed object
    generator = models.ForeignKey("planet.Generator", blank=True, null=True)
    # info attribute from Feedparser's Feed object
    info = models.CharField(_("Infos"), max_length=255, blank=True, null=True)
    # language name or code. language attribute from Feedparser's Feed object
    language = models.CharField(_("Language"), max_length=50, blank=True,
                                null=True)
    # global unique identifier for the feed
    guid = models.CharField(_("Global Unique Identifier"), max_length=32,
        blank=True, null=True, db_index=True)
    # icon attribute from Feedparser's Feed object
    icon_url = models.URLField(_("Icon URL"), blank=True, null=True)
    # image attribute from Feedparser's Feed object
    image_url = models.URLField(_("Image URL"), blank=True, null=True)

    # etag attribute from Feedparser's Feed object
    etag = models.CharField(_("Etag"), max_length=50, blank=True,
        null=True, db_index=True)
    # modified attribute from Feedparser's Feed object
    last_modified = models.DateTimeField(_("Last modified"), null=True,
        blank=True, db_index=True)
    # datetime when the feed was checked by last time
    last_checked = models.DateTimeField(_("Last checked"), null=True,
                                        blank=True)
    # in order to retrieve it or not
    is_active = models.BooleanField(_("Is active"), default=True,
                                    db_index=True,
        help_text=_("If disabled, this feed will not be further updated."))

    category = models.ForeignKey(Category, blank=True, null=True,
                                 db_index=True)

    site_objects = FeedManager()
    objects = models.Manager()

    class Meta:
        verbose_name = _("Feed")
        verbose_name_plural = _("Feeds")
        ordering = ('title', )

    def save(self, *args, **kwargs):
        if not self.blog:
            self.modified = self.etag = None

            try:
                USER_AGENT = settings.PLANET["USER_AGENT"]
            except (KeyError, AttributeError):
                print("""Please set the PLANET = {"USER_AGENT": <string>} in your settings.py""")
                exit(0)

            document = feedparser.parse(self.url, agent=USER_AGENT,
                                        modified=self.modified, etag=self.etag)

            self.site = Site.objects.get(pk=settings.SITE_ID)

            self.title = document.feed.get("title", "--")
            self.subtitle = document.feed.get("subtitle")
            blog_url = document.feed.get("link")
            self.rights = document.feed.get("rights") or document.feed.get("license")
            self.info = document.feed.get("info")
            self.guid = document.feed.get("id")
            self.image_url = document.feed.get("image", {}).get("href")
            self.icon_url = document.feed.get("icon")
            self.language = document.feed.get("language")
            self.etag = document.get("etag", '')
            self.last_modified = document.get("updated_parsed", datetime.now())

            self.blog, created = Blog.objects.get_or_create(
                url=blog_url, defaults={"title": self.title})

            generator_dict = document.feed.get("generator_detail", {})

            if generator_dict:
                self.generator, created = Generator.objects.get_or_create(
                    name=generator_dict.get("name", "--"),
                    link=generator_dict.get("link"),
                    version=generator_dict.get("version"))
            else:
                self.generator = None
        super(Feed, self).save(*args, **kwargs)

    def __str__(self):
        return '{} ({})'.format(self.title, self.url)

    @models.permalink
    def get_absolute_url(self):
        return ('planet.views.feed_detail', [str(self.id), self.get_slug()])

    def get_slug(self):
        return slugify(self.title) or "no-title"


@python_2_unicode_compatible
class PostAuthorData(models.Model):
    """
    This is the intermediate model that holds the information of the post authors
    """
    post = models.ForeignKey("planet.Post")
    author = models.ForeignKey("planet.Author")
    # True if this author is a contributor. False to tell he is the original
    # author of ths post
    is_contributor = models.BooleanField(_("Is Contributor?"), default=False)
    date_created = models.DateField(_("Date created"), auto_now_add=True)

    class Meta:
        verbose_name = _("Post Author Data")
        verbose_name_plural = _("Post Author Data")
        ordering = ("author", "post", "is_contributor")

    def __str__(self):
        author_type = self.is_contributor and "Contributor" or "Author"
        return '{} ({} - {})'.format(
            self.author.name, author_type, self.post.title)


@python_2_unicode_compatible
class Post(models.Model):
    """
    A feed contains a collection of posts. This model stores them.
    """
    feed = models.ForeignKey("planet.Feed", null=False, blank=False)
    title = models.CharField(_("Title"), max_length=255, db_index=True)
    authors = models.ManyToManyField("planet.Author", through=PostAuthorData)
    url = models.URLField(_("Url"), max_length=1000, db_index=True)
    guid = models.CharField(_("Guid"), max_length=32, db_index=True)
    content = models.TextField(_("Content"))
    comments_url = models.URLField(_("Comments URL"), blank=True, null=True)

    date_modified = models.DateTimeField(_("Date modified"), null=True,
        blank=True, db_index=True)
    date_created = models.DateTimeField(_("Date created"), auto_now_add=True)

    site_objects = PostManager()
    objects = models.Manager()

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ('-date_created', '-date_modified')
        unique_together = (('feed', 'guid'),)

    def __str__(self):

templates/planet/feeds/detail.html
{% extends "planet/base.html" %}
{% load i18n pagination_tags tagging_tags planet_tags %}
{% load url from future %}

{% block head_title %}{% trans "Feed" %}: {{ feed.title }}{% endblock %}

{% block extra_head %}
    <meta name="title" content="{% trans 'Feed' %}: {{ feed.title }}" />
    <meta name="description" content="{% trans 'Feed' %} {{ feed.title }}" />
    <meta name="robots" content="index, follow" />
    <link rel="canonical" href="http://{{ site.domain }}{{ feed.get_absolute_url }}"/>
{% endblock %}

{% block breadcrumb_section %}
    <li><a href="{% url 'planet.views.blogs_list' %}">Blogs</a> <span class="divider">/</span></li>
    <li><a href="{{ feed.blog.get_absolute_url }}">{{ feed.blog.title }}</a> <span class="divider">/</span></li>
    {% if tag %}
        <li>Feed: <a href="{{ feed.get_absolute_url }}">{{ feed.title }}</a> <span class="divider">/</span></li>
    {% endif %}
{% endblock %}
{% block breadcrumb_detail %}
    {% if tag %}
        <li class="active">Tag: {{ tag.name }}</li>
    {% else %}
        <li class="active">Feed: {{ feed.title }}</li>
    {% endif %}
{% endblock %}

{% block content %}
    {% if feed.icon %}
        <img src="{{ feed.icon }}" alt="{% trans 'Feed icon' %}" />
    {% endif %}
    <h1>{% trans "Feed" %}: {{ feed.title }}</h1>
    {% if feed.subtitle %}
        <p>{{ feed.subtitle|striptags }}</p>
    {% endif %}

    {% if not tag %}
    <table class="blog details table table-hover table-bordered">
        <tr>
            <th>{% trans 'Blog' %}</th><td>
            <a href="{{ feed.blog.get_absolute_url }}" class="feed" title="{% trans 'See details and posts for blog' %} {{ feed.blog.title }}">{{ feed.blog.title }}</a></td>
        </tr>
        <tr>
            <th>{% trans 'RSS 2.0 Feed' %}</th><td>
            <a href="{{ feed.url }}" class="feed" title="{% trans 'Subscribe to ' %} {{ feed.title }}">{{ feed.title }}</a></td>
        </tr>
        <tr>
            <th>{% trans 'web' %}</th><td><a href="{{ feed.blog.url }}" title="{% trans 'Go to the original blog' %}">{{ feed.blog.url }}</a></td>
        </tr>
        <tr>
            <th>{% trans 'Last Update' %}</th><td>{{ feed.last_checked|date:"m.d.Y" }}</td>
        </tr>
        <tr>
            <th>{% trans 'Posts' %}</th><td>{{ feed.post_set.count }}</td>
        </tr>
    </table>
    {% endif %}

    {% if tag %}
        <h2>{% trans 'Posts under tag' %}: <strong>{{ tag|safe }}</strong></h2>
    {% endif %}

    {% autopaginate posts 20 %}
    {% for post in posts %}
        <div class="post {% cycle 'even' 'odd' %} clearfix">
            {% post_details post "planet/posts/short.html" %}
        </div>
    {% endfor %}
    {% paginate %}
{% endblock %}

{% block right_column %}
    {# this is too slow % authors_for_feed feed %#}
    {% include 'planet/feeds/blocks/syndication_block.html' %}

    {% if tag %}
        <div>
            {% related_tags_for tag %}
        </div>
        <div>
            {% feeds_about tag %}
        </div>
    {% endif %}

    {% cloud_for_feed feed %}
{% endblock %}

templates/planet/feeds/form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% load devtags %}

{% block content %}
<main id="main" class="container" role="main">
    <div class="col-lg-12">
	    <div class="page-header">
	    	<h2>{% if form.instance.id %}
	    			{% trans 'Editar feed' %}
	    		{% else %}
	    			{% trans 'Agregar feed' %}
	    		{% endif %}
	    	</h2>
	    </div>
		<div class="col-lg-12">
			<div class="alert alert-dismissable alert-warning">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<h4>Warning!</h4>
				<p>Best check yo self, you're not looking too good. Nulla vitae elit libero, a pharetra augue. Praesent commodo cursus magna, <a href="#" class="alert-link">vel scelerisque nisl consectetur et</a>.</p>
			</div>
		</div>
	    {% crispy form %}
	</div>
</main>
{% endblock %}

templates/planet/feeds/list.html
{% extends "planet/base.html" %}
{% load i18n pagination_tags  %}

{% block head_title %}{% trans "Feeds list" %}{% endblock %}

{% block extra_head %}
    <meta name="title" content="{% trans 'Feeds list' %} " />
    <meta name="description" content="{% trans 'Feeds list' %} " />
    <meta name="robots" content="noindex, follow" />
{% endblock %}

{% block breadcrumb_section %}<li class="active">Feeds</li>{% endblock %}

{% block content %}
<h1>{% trans "Feeds" %}</h1>
<div class="feeds list">
    {% autopaginate feeds_list 50 %}
    <ul>
    {% for feed in feeds_list %}
        <li>
            <h2>
                <a href="{{ feed.get_absolute_url }}" class="feed" title="{% trans 'See the full list of post from this feed' %}">{{ feed.title }}</a>
            </h2>
            <table class="blog details table table-hover table-bordered">
                <tr>
                    <th>{% trans 'Feed' %}</th><td><a href="{{ feed.url }}" class="feed" title="{% trans 'Subscribe to this feed' %}">{{ feed.url }}</a></td>
                </tr>
                <tr>
                    <th>{% trans 'web' %}</th><td><a href="{{ feed.blog.url }}" title="{% trans 'Go to the original blog' %}">{{ feed.blog.url }}</td>
                </tr>
                <tr>
                    <th>{% trans 'browse' %}</th><td><a href="{{ feed.get_absolute_url }}" class="feed" title="{% trans 'See the full list of posts from this feed' %}">{% trans 'latest posts' %}</a></td>
                </tr>
            </table>
        </li>
    {% endfor %}
    {% paginate %}
</div>
{% endblock %}

templates/planet/feeds/list_for_tag.html
{% extends "planet/base.html" %}
{% load i18n pagination_tags %}
{% load url from future %}

{% block head_title %}{% trans "Feeds under tag" %} {{ tag|safe }}{% endblock %}

{% block extra_head %}
    <meta name="title" content="{% trans 'Feeds for tag' %} {{ tag|safe }}" />
    <meta name="description" content="{% trans 'Feeds for tag' %} {{ tag|safe }} " />
    <meta name="robots" content="noindex, follow" />
{% endblock %}

{% block breadcrumb_section %}
    <li><a href="{% url 'planet.views.tags_cloud' %}">Tags</a> <span class="divider">/</span></li>
    <li><a href="{% url 'planet.views.tag_detail' tag.name %}">{{ tag|safe }}</a> <span class="divider">/</span></li>
{% endblock %}
{% block breadcrumb_detail %}<li class="active">{% trans 'Blog Feeds' %}</li>{% endblock %}

{% block content %}
<h1>{% trans 'Feeds talking about' %} {{ tag|safe }}</h1>
<div class="feeds list">
    {% autopaginate feeds_list 40 %}
    {% for feed in feeds_list %}
        <p>
            <a href="{{ feed.feed_url }}" title="{% trans 'Subscribe to feed of' %} {{ feed.title }}">
                <img src="{{ MEDIA_URL }}images/feed.png" alt="Feed">
            </a>
            <a class="nombre" href="{% url 'planet_by_tag_feed_detail' feed.id feed.get_slug tag.name %}" title="{{ feed.title }}">
                {{ feed.title }}
            </a>
        </p>
    {% endfor %}
    {% paginate %}
</div>
{% endblock %}