events/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from .views import (EventDetail,
                    EventList,
                    EventCreate,
                    EventUpdate,
                    EventDelete,
                    EventsFeed)

urlpatterns = patterns('',
                       url(r'^$', EventList.as_view(), name='events_list_all'),
                       url(r'^rss$', EventsFeed(), name='events_feed'),
                       url(r'^(?P<pk>\d+)/$', EventDetail.as_view(), name='detail'),
                       url(r'^add/$', EventCreate.as_view(), name='add'),
                       url(r'^(?P<pk>\d+)/edit/$', EventUpdate.as_view(), name='edit'),
                       url(r'^(?P<pk>\d+)/delete/$', EventDelete.as_view(), name='delete'),
                       )

faq/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from .views import (
    list_all,
)

urlpatterns = patterns('', url(r'^$', list_all, name='faq_all'),)

planet/urls.py
# -*- coding: utf-8 -*-
try:
    # Django 1.6
    from django.conf.urls import patterns, url, include
except ImportError:
    # Django < 1.6
    from django.conf.urls.defaults import patterns, url

from django.contrib.sitemaps import views as sitemaps_views
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required

from planet.views import (FeedFormView, BlogByUserList, BlogDelete,
                          FeedDelete, PostDelete)
from planet.feeds import PostFeed, AuthorFeed, AuthorTagFeed, TagFeed
from planet.sitemaps import planet_sitemaps_dict


urlpatterns = patterns('planet.views',
                       url(r'^blogs/(?P<blog_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "blog_detail", name="planet_blog_detail"),
                       url(r'^blogs/(?P<blog_id>\d+)/$', "blog_detail"),
                       url(r'^blogs/(?P<pk>\d+)/delete$',
                           login_required(BlogDelete.as_view()), name="planet_blog_delete"),
                       url(r'^blogs/$', "blogs_list", name="planet_blog_list"),
                       url(r'^blogs/my_blogs/$', login_required(BlogByUserList.as_view()),
                           name="planet_blog_list_by_user"),

                       url(r'^feeds/add/$', login_required(FeedFormView.as_view()),
                           name="feed_add"),
                       url(r'^feeds/(?P<feed_id>\d+)/delete/$',
                           login_required(FeedDelete.as_view()), name="feed_delete"),
                       url(r'^feeds/(?P<feed_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/tags/(?P<tag>.*)/$',
                           "feed_detail", name="planet_by_tag_feed_detail"),
                       url(r'^feeds/(?P<feed_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "feed_detail", name="planet_feed_detail"),
                       url(r'^feeds/(?P<feed_id>\d+)/$', "feed_detail"),
                       url(r'^feeds/$', "feeds_list", name="planet_feed_list"),

                       url(r'^authors/(?P<author_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/tags/(?P<tag>.*)/$',
                           "author_detail", name="planet_by_tag_author_detail"),
                       url(r'^authors/(?P<author_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "author_detail", name="planet_author_detail"),
                       url(r'^authors/(?P<author_id>\d+)/$', "author_detail"),
                       url(r'^authors/$', "authors_list",
                           name="planet_author_list"),

                       url(r'^tags/(?P<tag>.*)/feeds/$',
                           "tag_feeds_list", name="planet_tag_feed_list"),
                       url(r'^tags/(?P<tag>.*)/authors/$',
                           "tag_authors_list", name="planet_tag_author_list"),
                       url(r'^tags/(?P<tag>.*)/$', "tag_detail",
                           name="planet_tag_detail"),
                       url(r'^tags/$', "tags_cloud", name="planet_tag_cloud"),

                       url(r'^opml/$', "opml", name="planet_opml"),
                       url(r'^foaf/$', "foaf", name="planet_foaf"),

                       url(r'^posts/(?P<post_id>\d+)/(?P<slug>[a-zA-Z0-9_\-]+)/$',
                           "post_detail", name="planet_post_detail"),
                       url(r'^posts/(?P<pk>\d+)/$', login_required(PostDelete.as_view()),
                           name="planet_post_delete"),
                       url(r'^posts/(?P<post_id>\d+)/$', "post_detail"),
                       url(r'^posts/$', "posts_list", name="planet_post_list"),

                       url(r'^search/$', "search", name="planet_search"),

                       url(r'^$', "index", name="planet_index"),
                       )

# Feed's urls
urlpatterns += patterns('',
                        url(r'^posts/feeds/rss/$', PostFeed(),
                            name="planet_rss_feed"),
                        url(r'^feeds/rss/tags/(?P<tag>.*)/$',
                            TagFeed(), name="planet_tag_rss_feed"),
                        url(r'^feeds/rss/authors/(?P<author_id>\d+)/$',
                            AuthorFeed(), name="planet_author_rss_feed"),
                        url(r'^feeds/rss/authors/(?P<author_id>\d+)/tags/(?P<tag>.*)/$',
                            AuthorTagFeed(), name="planet_tag_author_rss_feed"),
                        )

# sitemaps
urlpatterns += patterns('',
                        url(r'^sitemap.xml$',
                            cache_page(86400)(sitemaps_views.index),
                            {'sitemaps': planet_sitemaps_dict, 'sitemap_url_name': 'sitemaps'}),
                        url(r'^sitemap-(?P<section>.+)\.xml$',
                            cache_page(86400)(sitemaps_views.sitemap),
                            {'sitemaps': planet_sitemaps_dict}, name='sitemaps'),
                        )

pyarweb/urls.py
# -*- coding: utf-8 -*-


"""URLS configurations for PyAr Web."""


from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin
from waliki.settings import WALIKI_SLUG_PATTERN

from .views import buscador, irc, old_url_redirect


admin.autodiscover()


urlpatterns = patterns(
    '',
    # Static files
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    # Media files
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    url(r'^irc/$', irc, name='irc'),
    url(r'^buscador/$', buscador, name='buscador'),

    url(r'^$', 'community.views.homepage', name='homepage'),
    url(r'^aprendiendo-python/', 'community.views.learning', name='aprendiendo'),
    url(r'^nosotros/', 'community.views.about_pyar', name='about_pyar'),
    url(r'^miembros/', 'community.views.members', name='pyar_members'),
    url(r'^lista/', 'community.views.mailing_list', name='mailing_list'),

    url(r'^noticias/', include('news.urls')),
    url(r'^empresas/', include('pycompanies.urls', namespace='companies')),
    url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^trabajo/', include('jobs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^eventos/', include('events.urls', namespace='events')),
    # Descomentar cuando planet este funcionando
    # url(r'^planeta/', include('planet.urls')),
    # No se que va a pasar con la app de newbie, lanzamos primer release y
    # lo comento hasta que se decida que se hace
    # url(r'^newbie/', include('newbie.urls')),
    # No se que va a pasar con la app de project, lanzamos primer release y
    # lo comento hasta que se decida que se hace
    # url(r'^projects/', include('projects.urls')),
    # url(r'^faq/', include('faq.urls')),
    url(r'^wiki/', include('waliki.urls')),
    url(r'^(pyar/)?(?P<slug>' + WALIKI_SLUG_PATTERN + ')/?',
        old_url_redirect, name='old_url_redirect'),
)

events/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse


class Event(models.Model):
    """A PyAr events."""

    owner = models.ForeignKey(User)
    name = models.CharField(max_length=100, verbose_name=_('Título'))
    description = models.TextField(verbose_name=_('Descripcion'))
    place = models.CharField(max_length=100, verbose_name=_('Lugar'))
    address = models.CharField(max_length=100, verbose_name=_('Direccion'))
    url = models.URLField(blank=True, null=True)
    start_at = models.DateField(verbose_name=_('Comienza a las'))
    end_at = models.DateField(verbose_name=_('Termina a las'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s by %s" % (self.name, self.owner)

    def get_absolute_url(self):
        return reverse('events:detail', args=[self.id])

events/forms.py
from django import forms
from django_summernote.widgets import SummernoteInplaceWidget
from django.utils.translation import ugettext_lazy as _

from bootstrap3_datetime.widgets import DateTimePicker
from crispy_forms.layout import Submit, Reset, Layout, Div, Field
from crispy_forms.helper import FormHelper

from .models import Event


class EventForm(forms.ModelForm):

    description = forms.CharField(widget=SummernoteInplaceWidget())

    start_at = forms.DateField(
        required=True,
        label=_('Comienza'),
        widget=DateTimePicker(
            options={
                "format": "DD/MM/YYYY"
            }
        )
    )

    end_at = forms.DateField(
        required=True,
        label=_('Finaliza'),
        widget=DateTimePicker(
            options={
                "format": "DD/MM/YYYY"
            }
        )
    )

    class Meta:
        model = Event
        fields = (
            'name',
            'description',
            'place',
            'address',
            'url',
            'start_at',
            'end_at'
        )

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.form_method = "post"
        self.helper.add_input(Submit('job_submit', _('Guardar')))
        self.helper.add_input(Reset('job_reset', _('Limpiar'), css_class='btn-default'))
        self.helper.layout = Layout(
            Div(
                'name',
                'description',
                'place',
                'address',
                'url',
                'start_at',
                'end_at',
            )
        )

    def clean(self):
        cleaned_data = super(EventForm, self).clean()
        start_at = cleaned_data.get('start_at')
        end_at = cleaned_data.get('end_at')
        if start_at is not None and end_at is not None:
            if start_at > end_at:
                msg = 'La fecha de inicio es menor a la fecha de finalizacion'
                self._errors['start_at'] = [_(msg)]
                self._errors['end_at'] = [_(msg)]
        return cleaned_data

    def save(self, *args, **kwargs):
        super(EventForm, self).save(*args, **kwargs)
        self.instance.save()

events/views.py
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.edit import (CreateView,
                                       UpdateView,
                                       DeleteView)

from braces.views import LoginRequiredMixin

from community.views import OwnedObject

from .forms import EventForm
from .models import Event
from .mixins import EventMixin

from django.contrib.syndication.views import Feed
from django.core.urlresolvers import reverse_lazy


class EventsFeed(Feed):
    title = "Feed de Próximos Eventos de PyAr"
    link = reverse_lazy("events:events_list_all")
    description = "Eventos de Python Argentina y relacionados"
    description_template = "events/event_detail_body.html"

    def items(self):
        return Event.objects.filter(end_at__gte=timezone.now()).order_by('-updated_at')[:10]

    def item_title(self, item):
        return item.name

    def item_pubdate(self, item):
        return item.created_at

    def item_updateddate(self, item):
        return item.updated_at

    def author_name(self, item):
        if item:
            return str(item.owner)
        return ''


class EventList(ListView):
    queryset = Event.objects.filter(
        end_at__lt=timezone.now()).order_by('-updated_at')
    paginate_by = 5
    context_object_name = "eventos_pasados"

    def get_context_data(self, **kwargs):
        context = super(EventList, self).get_context_data(**kwargs)
        context['eventos_proximos'] = Event.objects.filter(
            end_at__gte=timezone.now()).order_by('-updated_at')

        return context


class EventDetail(EventMixin, DetailView):
    context_object_name = "event"


class EventCreate(LoginRequiredMixin, EventMixin, CreateView):
    form_class = EventForm

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(EventCreate, self).form_valid(form)


class EventUpdate(LoginRequiredMixin, EventMixin, OwnedObject, UpdateView):
    form_class = EventForm


class EventDelete(LoginRequiredMixin, OwnedObject, DeleteView):
    model = Event
    success_url = reverse_lazy("events_list_all")

templates/events/event_confirm_delete.html
{% extends "base.html" %}

{% load i18n %}

{% load devtags %}

{% block content %}

	<main id="main" class="container" role="main">
	    <div class="row">
	        <div class="col-md-12">
		        <form method="post">{% csrf_token %}
				    {% trans "Are you sure you want to delete" %} "{{ object.name }}" ?
				    <input type="submit" value="Yes" class="btn btn-danger">
				    <a href="{% url 'events:events_list_all' %}" class="btn btn-default">No</a>
				</form>
	        </div>
	    </div>
	</main>

{% endblock %}

templates/events/event_detail.html
{% extends "base.html" %}

{% load i18n %}

{% load devtags %}

{% block title %}
    {{ event.name }}
{% endblock title %}


{% block stylesheets %}
  <link rel="stylesheet" href="/static/css/event_map.css">
{% endblock %}

{% block javascripts %}
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <script src="/static/js/event_detail.js"></script>
{% endblock %}


{% block content %}

	<main id="main" class="container" role="main">
	    <div class="row">
       <div class="col-md-12">

        <div class="page-header">
          <h1>
            {{ event.name }}

            {% if event.owner == user %}
              <span class="section-button-group pull-right">
                <a class="btn btn-default" href="{% url 'events:edit' event.id %}">
                  {% trans 'Modificar' %}
                </a>
                <a class="btn btn-danger" href="{% url 'events:delete' event.id %}">
                  {% trans 'Borrar' %}
                </a>
              </span>
            {% endif %}
          </h1>

          <small>
            {{ event.updated_at }} {% trans 'por' %} {{ event.owner}}
          </small>
        </div>

       </div>
      </div>

      <div class="row">

      {% include "events/event_detail_body.html" with obj=event %}

      </div>

            <input type="hidden" id="id_lat" value="{{ event.lat }}">
            <input type="hidden" id="id_lng" value="{{ event.lng }}">
            <input type="hidden" id="id_zoom" value="{{ event.zoom }}">
	        </div>
	    </div>
	</main>

{% endblock %}

templates/events/event_detail_body.html
{% load i18n %}


            <div class="col-md-6">

            <h3>{% trans "¿De qué se trata?" %}</h3>
            <p>{{ obj.description|safe }}</p>

          </div>

          <div class="col-md-6">

            <h3>{% trans "¿Cuándo?" %}</h3>
            {% if obj.start_at %}
              <p>{% trans "Comienza" %}: {{ obj.start_at }}</p>
            {% endif %}

            {% if obj.end_at %}
              <p>{% trans "Termina" %}: {{ obj.end_at }}</p>
            {% endif %}

            <h3>{% trans "¿Dónde?" %}</h3>
            <p>{{ obj.place }} | {{ obj.address }}</p>

            {% if obj.url %}
              <h3>{% trans "Más Información" %}</h3>
              <p>
                <a href="{{ obj.url }}">{{ obj.url }}</a>
              </p>
            {% endif %}

templates/events/event_form.html
{% extends "base.html" %}

{% load i18n %}
{% load devtags %}
{% load crispy_forms_tags %}

{% block stylesheets %}
  <link rel="stylesheet" href="/static/css/event_map.css">
  {{ form.media.css }}
{% endblock %}

{% block content %}

  <main id="main" class="container" role="main">
    <div class="col-lg-12">
      <div class="page-header">
        <h2>
          {% if form.instance.id %}
            {% trans 'Editar Evento' %}
          {% else %}
            {% trans 'Agregar Evento' %}
          {% endif %}

          <span class="section-button-group pull-right">
                <a href="{% url 'events:events_list_all' %}" class="btn btn-info">
                  {% trans "Volver a eventos" %}
                </a>
            </span>
        </h2>
      </div>

      {% crispy form %}

    </div>
  </main>

{% endblock %}

{% block javascripts %}

  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <script src="/static/js/event_form.js"></script>
  
  {{ form.media.js }}

{% endblock %}

templates/events/event_list.html
{% extends "base_site.html" %}

{% load i18n %}

{% load devtags %}

{% block title %}Eventos {% endblock %}

{% block left-column %}

  <!-- Proximos eventos -->

  <section>
    <div class="page-header">
      <h2>
        {% trans "Proximos Eventos" %}

        {% if user.is_authenticated %}
          <span class="section-button-group pull-right">
            <a href="{% url 'events:add' %}" class="btn btn-info">{% trans "Agregar" %}</a>
          </span>
        {% endif %}

        <div class="pull-right">
                <a href="{% url 'events:events_feed' %}" class="badge">
                    <i class="fa fa-rss"></i> RSS
                </a>
           </div>


      </h2>


    </div>


      {% for event in eventos_proximos %}

          <article class="list-group-item">
              <h4 class="list-group-item-heading">
                <a href="{% url 'events:detail' event.id %}">
                  {{ event.name }}
                </a> |
                <small>{{ event.start_at }}</small>
              </h4>
              <p class="list-group-item-text">{{ event.description|striptags| truncatewords:"20" }}</p>
            </article>
      {% empty %}
        <article class="list-group-item">
          <p class="list-group-item-text">{% trans "No hay eventos a futuro" %}</p>
        </article>
      {% endfor %}

      <br>

      <header class="page-header">
          <h2>
            {% trans "Eventos pasados" %}
          </h2>
      </header>

      {% for event in eventos_pasados %}

          <article class="list-group-item">
              <h4 class="list-group-item-heading">
                <a href="{% url 'events:detail' event.id %}">
                  {{ event.name }}
                </a> |
                <small>{{ event.start_at }}</small>
              </h4>
              <p class="list-group-item-text">{{ event.description|striptags|truncatewords:"20" }}</p>
            </article>

      {% empty %}
        <article class="list-group-item">
          <p class="list-group-item-text">{% trans "No hay eventos pasados" %}</p>
        </article>
      {% endfor %}

      <div class="pagination">
          <span class="step-links">
              {% if page_obj.has_previous %}
              <a href="?page={{ page_obj.previous_page_number }}">{% trans 'anterior' %}</a>
              {% endif %}

              <span class="current">
                {% trans "Pagina" %} {{ page_obj.number }} {% trans 'de' %} {{ page_obj.paginator.num_pages }}.
              </span>

              {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">{% trans 'siguiente' %}</a>
              {% endif %}
          </span>
      </div>

  </section>
{% endblock %}

templates/events/next_events.html
{% for event in events %}
    <article class="list-group-item">
      <h4 class="list-group-item-heading">
        <a href="{% url 'events:detail' event.id %}">
          {{ event.name }}
        </a>
      </h4>
      
      <p class="list-group-item-text">
        <span>{{ event.start_at|date:"DATE_FORMAT" }}</span> | 
        <span>{{ event.start_at|time:"TIME_FORMAT" }}</span> | 
        <span>{{ event.place }}</span>
      </p>
    </article>

{% empty %}
  <article class="list-group-item">
    <p class="list-group-item-text">No hay eventos a futuro</p>
  </article>
{% endfor %}